In [1]:
# Q1. Create a Pandas Series from a list of integers.
import pandas as pd
import numpy as np
integer=pd.Series([10,20,30,40,60,np.nan])
print(integer)

0    10.0
1    20.0
2    30.0
3    40.0
4    60.0
5     NaN
dtype: float64

In [2]:
# Q2. Create a Series from a dictionary with custom index

c_dict=pd.Series({"name":"vaishnavi","age":23,"gender":"female"})
print(c_dict)

name      vaishnavi
age              23
gender       female
dtype: object

In [3]:
# Q3. Access elements using index labels.
print(c_dict.loc[["name","age"]])
print(integer.iloc[0:2])

name    vaishnavi
age            23
dtype: object
0    10.0
1    20.0
dtype: float64

In [4]:
#  Q4. Perform arithmetic operations on a Series.
print(integer+5)
print(integer-5)
print(integer/5)
print(integer//5)

0    15.0
1    25.0
2    35.0
3    45.0
4    65.0
5     NaN
dtype: float64
0     5.0
1    15.0
2    25.0
3    35.0
4    55.0
5     NaN
dtype: float64
0     2.0
1     4.0
2     6.0
3     8.0
4    12.0
5     NaN
dtype: float64
0     2.0
1     4.0
2     6.0
3     8.0
4    12.0
5     NaN
dtype: float64

In [5]:
#  Q5. Find mean, min, max of a Series
print(integer.mean())
print(integer.min())
print(integer.max())

32.0
10.0
60.0

In [6]:
# Q6. Apply conditional filtering on a Series.
print(integer[integer>20])
print(integer[integer<10])

2    30.0
3    40.0
4    60.0
dtype: float64
Series([], dtype: float64)

In [7]:
# Q7. Replace values in a Series.

integer.replace(10,2222)

0    2222.0
1      20.0
2      30.0
3      40.0
4      60.0
5       NaN
dtype: float64

In [8]:
# Q8. Convert Series data type.

integer.astype(float)

0    10.0
1    20.0
2    30.0
3    40.0
4    60.0
5     NaN
dtype: float64

In [9]:
# Q9. Check for null values in Series.

integer.isnull()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [10]:
# Q10. Fill missing values in Series.
integer.fillna("hello")

0     10.0
1     20.0
2     30.0
3     40.0
4     60.0
5    hello
dtype: object

In [11]:
#  Q11. Create DataFrame from a list.

data=pd.DataFrame(["name","age","gender","mobile_no"],columns=["information"])
print(data)

  information
0        name
1         age
2      gender
3   mobile_no

In [12]:
# Q12. Create DataFrame from a dictionary.
dataframe=pd.DataFrame({
    "name":["aa","bb","cc","dd"],
    "location":["nagpur","pune","mumbai","banglour"]
}
)
print(dataframe)

  name  location
0   aa    nagpur
1   bb      pune
2   cc    mumbai
3   dd  banglour

In [13]:
dataframe=["name"]
print(dataframe)

['name']

In [14]:
# Q13. Create DataFrame from list of dictionaries.

dataframe = pd.DataFrame([{"age":23}, {"contact":91569516}])
print(dataframe)

    age     contact
0  23.0         NaN
1   NaN  91569516.0

In [15]:
# Q14. Display DataFrame structure (shape, columns, dtypes).

print(dataframe.shape)
print(dataframe.columns)
print(dataframe.dtypes)

(2, 2)
Index(['age', 'contact'], dtype='object')
age        float64
contact    float64
dtype: object

In [16]:
# Q15. Select single column from DataFrame.

dataframe["name"]

KeyError: 'name'

In [17]:
# Q16. Select multiple columns.

dataframe[["name","location"]]

KeyError: "None of [Index(['name', 'location'], dtype='object')] are in the [columns]"

In [18]:
# Q17. Add new column with scalar value.

update=dataframe["location"]="pune"

dataframe

    age     contact location
0  23.0         NaN     pune
1   NaN  91569516.0     pune

In [19]:
# Q18. Add column using Series.

column_add = dataframe["state"]=pd.Series(["mh"])
dataframe
dataframe.fillna("mh") # this will not fill permanantaly

    age     contact location state
0  23.0          mh     pune    mh
1    mh  91569516.0     pune    mh

In [20]:
# Q19. Rename columns using `rename()`.

dataframe.rename(columns={"state": "re_state"})

    age     contact location re_state
0  23.0         NaN     pune       mh
1   NaN  91569516.0     pune      NaN

In [21]:
# Q20. Rename multiple columns.

dataframe.rename(columns={"name":"short_name","location":"new_location","state":"new_state"})

    age     contact new_location new_state
0  23.0         NaN         pune        mh
1   NaN  91569516.0         pune       NaN

Section 2: Indexing, Selection & Slicing (Q21–Q40)

In [22]:

# Q21. Select rows using `loc`.

dataframe.loc[1]

age                NaN
contact     91569516.0
location          pune
state              NaN
Name: 1, dtype: object

In [23]:
# Q22. Select rows using `iloc`.

dataframe.iloc[0:3,1:3]

      contact location
0         NaN     pune
1  91569516.0     pune

In [24]:
# Q23. Access specific row and column.

dataframe.iloc[1:2] # start : stop

   age     contact location state
1  NaN  91569516.0     pune   NaN

In [25]:
# Q24. Select subset using multiple rows & columns.

dataframe.iloc[[0,2], [0,2]]

IndexError: positional indexers are out-of-bounds

In [26]:
# Q25. Apply conditional filtering using `loc`.

# dataframe.loc[dataframe["location"] ==nagpur, ["col1","col2"]]

In [27]:
#  Q26. Slice rows using index range.
dataframe.iloc[0:2]

    age     contact location state
0  23.0         NaN     pune    mh
1   NaN  91569516.0     pune   NaN

In [28]:
# Q27. Slice columns using labels.

dataframe.loc[:, "col1":"col3"]

Empty DataFrame
Columns: []
Index: [0, 1]

In [29]:
#  Q28. Slice columns using position.

dataframe.iloc[:, 1:4]

      contact location state
0         NaN     pune    mh
1  91569516.0     pune   NaN

In [30]:
# Q29. Perform combined row & column slicing.
dataframe.iloc[1:3,1:3] 
# 1:3 is row 
# 1:3 is column

      contact location
1  91569516.0     pune

In [33]:
# Q30. Set a column as index.

std = {
    "roll_no": [1,2,3,4,5],
    "Name":["X","Y","Z","Q","R"],
    "Marks":[90,80,89,86,85]
}

std["Name"]

['X', 'Y', 'Z', 'Q', 'R']

In [56]:
# Q31. Create hierarchical index (MultiIndex).

dataframe.set_index(["name","location"])

KeyError: "None of ['name'] are in the columns"

In [57]:
# Q32. Reset index.
dataframe.reset_index()

   index   age     contact location state
0      0  23.0         NaN     pune    mh
1      1   NaN  91569516.0     pune   NaN

In [58]:
# Q33. Reset multi-index.

dataframe.reset_index()

   index   age     contact location state
0      0  23.0         NaN     pune    mh
1      1   NaN  91569516.0     pune   NaN

In [59]:
# Q34. Convert index to column.

dataframe.reset_index(drop=False)

   index   age     contact location state
0      0  23.0         NaN     pune    mh
1      1   NaN  91569516.0     pune   NaN

In [60]:
# Q35. Use drop option in `reset_index`.

dataframe.reset_index(drop=True)

    age     contact location state
0  23.0         NaN     pune    mh
1   NaN  91569516.0     pune   NaN

In [61]:
dataframe

    age     contact location state
0  23.0         NaN     pune    mh
1   NaN  91569516.0     pune   NaN

In [62]:
#  Q36. Perform label-based indexing.
dataframe.loc[0:1]

    age     contact location state
0  23.0         NaN     pune    mh
1   NaN  91569516.0     pune   NaN

In [63]:
# Q37. Perform position-based indexing.

dataframe.iloc[0:1]

    age  contact location state
0  23.0      NaN     pune    mh

In [64]:
# Q38. Access first N rows.

dataframe.head(2)

    age     contact location state
0  23.0         NaN     pune    mh
1   NaN  91569516.0     pune   NaN

In [65]:
#  Q39. Access last N rows.

dataframe.tail(2)

    age     contact location state
0  23.0         NaN     pune    mh
1   NaN  91569516.0     pune   NaN

In [66]:
# Q40. Extract random sample from DataFrame.

# dataframe

Section 3: Data Cleaning (Q41–Q60)

In [67]:
# Q41. Detect missing values using `isnull()`.

dataframe.isnull()

     age  contact  location  state
0  False     True     False  False
1   True    False     False   True

In [68]:
# Q42. Drop missing values using `dropna()`
dataframe.dropna()

Empty DataFrame
Columns: [age, contact, location, state]
Index: []

In [69]:
# Q43. Fill missing values with a constant.
dataframe.fillna(0)

    age     contact location state
0  23.0         0.0     pune    mh
1   0.0  91569516.0     pune     0

In [70]:
#  Q44. Fill missing values using mean/median.

print(integer.mean())
print(integer.median())

32.0
30.0

In [71]:
# Q45. Use forward fill and backward fill.

dataframe.ffill()

    age     contact location state
0  23.0         NaN     pune    mh
1  23.0  91569516.0     pune    mh

In [72]:
dataframe.bfill()

    age     contact location state
0  23.0  91569516.0     pune    mh
1   NaN  91569516.0     pune   NaN

In [83]:
# Q46. Convert data type using `astype()`.

dataframe["index"] = dataframe["index"].astype(float)

print(dataframe.dtypes)

KeyError: 'index'

In [84]:
# Q47. Clean string column using `.str.lower()`.

dataframe["name"].str.lower()

KeyError: 'name'

In [86]:
#  Q48. Trim whitespace in strings.

dataframe["name"].str.strip()

KeyError: 'name'

In [82]:
# Q49. Replace substring in column

dataframe["name"].str.replace("name","name_new")

KeyError: 'name'

In [119]:
# Q50. Extract part of string using `.str`
std = {
    "roll_no": [1,2,3,4,5],
    "Name":["X","Y","Z","Q","R"],
    "Marks":[90,80,89,86,85]
}

df = pd.DataFrame(std)


print(df["Name"].str[:3])

0    X
1    Y
2    Z
3    Q
4    R
Name: Name, dtype: object

In [120]:
df

   roll_no Name  Marks
0        1    X     90
1        2    Y     80
2        3    Z     89
3        4    Q     86
4        5    R     85

In [121]:
# Q51. Detect duplicate rows.
df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [122]:
df

   roll_no Name  Marks
0        1    X     90
1        2    Y     80
2        3    Z     89
3        4    Q     86
4        5    R     85

In [123]:
# Q52. Remove duplicates using `drop_duplicates()

df.drop_duplicates()

   roll_no Name  Marks
0        1    X     90
1        2    Y     80
2        3    Z     89
3        4    Q     86
4        5    R     85

In [124]:
# Q53. Rename row labels.

print(df.rename(index={"Name": "name"}))

   roll_no Name  Marks
0        1    X     90
1        2    Y     80
2        3    Z     89
3        4    Q     86
4        5    R     85

In [125]:
df

   roll_no Name  Marks
0        1    X     90
1        2    Y     80
2        3    Z     89
3        4    Q     86
4        5    R     85

In [126]:
# Q54. Handle inconsistent data.

df["Name"] =df["Name"].str.strip().str.lower().str.replace("X", "xx")
df

   roll_no Name  Marks
0        1    x     90
1        2    y     80
2        3    z     89
3        4    q     86
4        5    r     85

In [127]:
df

   roll_no Name  Marks
0        1    x     90
1        2    y     80
2        3    z     89
3        4    q     86
4        5    r     85

In [128]:
# Q55. Replace values in DataFrame.

df.replace("q","qq")

   roll_no Name  Marks
0        1    x     90
1        2    y     80
2        3    z     89
3        4   qq     86
4        5    r     85

In [129]:
# Q56. Detect outliers in a column.

In [130]:
#  Q57. Handle outliers using clipping.

# df["Marks"] = df["Marks"].clip(lower=40, upper=20)
print(df)

   roll_no Name  Marks
0        1    x     90
1        2    y     80
2        3    z     89
3        4    q     86
4        5    r     85

In [131]:
# Q58. Standardize column names
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

In [132]:
df

   roll_no name  marks
0        1    x     90
1        2    y     80
2        3    z     89
3        4    q     86
4        5    r     85

In [133]:
# Q59. Handle mixed data types in a column.

pd.to_numeric(df["marks"], errors="coerce")

0    90
1    80
2    89
3    86
4    85
Name: marks, dtype: int64

In [134]:
# Q60. Remove special characters from text data.
df2= pd.DataFrame({
    "Name": ["Ali@ce", "Bo#b", "Cha$rli%e"]
})

df2["Name"] = df2["Name"].str.replace(r"[^a-zA-Z0-9]", "", regex=True)

print(df2)

      Name
0    Alice
1      Bob
2  Charlie

Section 4: Data Manipulation (Q61–Q80)
<!--  -->

In [135]:
# Q61. Filter rows using AND condition.
df[(df["marks"] >= 40) & (df["roll_no"] <= 2)]

   roll_no name  marks
0        1    x     90
1        2    y     80

In [140]:
# Q62. Filter rows using OR condition.

df[(df["marks"]>=60) | (df["name"]== "Y" )]

   roll_no name  marks
0        1    x     90
1        2    y     80
2        3    z     89
3        4    q     86
4        5    r     85

In [149]:
# Q63. Filter rows using NOT condition.

df[~(df["marks"] > 85)]

   roll_no name  marks
1        2    y     80
4        5    r     85

In [150]:
#  Q64. Sort DataFrame by column values.

df.sort_values("name")

   roll_no name  marks
3        4    q     86
4        5    r     85
0        1    x     90
1        2    y     80
2        3    z     89

In [151]:
# Q65. Sort DataFrame by index.
df.sort_index()

   roll_no name  marks
0        1    x     90
1        2    y     80
2        3    z     89
3        4    q     86
4        5    r     85

In [154]:
# Q66. Add calculated column.

df["cal_cu"]=df["roll_no"]*df["marks"]
df

   roll_no name  marks  cal_cu
0        1    x     90      90
1        2    y     80     160
2        3    z     89     267
3        4    q     86     344
4        5    r     85     425

In [155]:
# Q67. Remove column using `drop()`

df.drop(columns=["cal_cu"])

   roll_no name  marks
0        1    x     90
1        2    y     80
2        3    z     89
3        4    q     86
4        5    r     85

In [156]:
df

   roll_no name  marks  cal_cu
0        1    x     90      90
1        2    y     80     160
2        3    z     89     267
3        4    q     86     344
4        5    r     85     425

In [157]:
# Q68. Remove rows using `drop()`
df.drop(index=[0, 3])

   roll_no name  marks  cal_cu
1        2    y     80     160
2        3    z     89     267
4        5    r     85     425

In [159]:
# Q69. Use `map()` on a column

df["name"].map({"y":8,"r":6})

0    NaN
1    8.0
2    NaN
3    NaN
4    6.0
Name: name, dtype: float64

In [166]:
#  Q70. Apply function using `apply()`.

df[["marks"]].apply(sum, axis=0)

marks    430
dtype: int64