## 🔹 Section 1: Basics & Series (Q1–Q20)

---

### Q1. Create a Pandas Series from a list of integers.
> 💡 **Hint:** Use `pd.Series([...])`. The default index starts from 0.

In [1]:
import pandas as pd

s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
print(s1)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

### Q2. Create a Series from a dictionary with custom index.
> 💡 **Hint:** Pass a `dict` to `pd.Series()`. Keys become the index labels automatically.

In [2]:
s2 = pd.Series({'Math':90,'Science':95,'English':88})
print(s2)

Math       90
Science    95
English    88
dtype: int64

### Q3. Access elements using index labels.
> 💡 **Hint:** Use `s["label"]` for a single value, `s[["a","b"]]` for multiple, and `s["a":"c"]` for a range. Label slices are **inclusive** on both ends.

In [3]:
employees = pd.DataFrame({
    'Name':['John','Mary','Alice','Bob'],
    'Department':['IT','HR','IT','Finance'],
    'Salary':[50000,60000,55000,70000]
},index = ['E1','E2','E3','E4'])

print(employees)

     Name Department  Salary
E1   John         IT   50000
E2   Mary         HR   60000
E3  Alice         IT   55000
E4    Bob    Finance   70000

In [9]:
print(employees.loc[:,'Name'])

print(employees.loc[['E1','E2']])

print(employees.loc['E1':'E3'])

E1     John
E2     Mary
E3    Alice
E4      Bob
Name: Name, dtype: str
    Name Department  Salary
E1  John         IT   50000
E2  Mary         HR   60000
     Name Department  Salary
E1   John         IT   50000
E2   Mary         HR   60000
E3  Alice         IT   55000

### Q4. Perform arithmetic operations on a Series.
> 💡 **Hint:** Use `+`, `-`, `*`, `/`, `//`, `%`, `**` directly on the Series. Operations are **element-wise** and **index-aligned**.

In [17]:
# it creates new series original unchanged 
s = pd.Series([10,20,30,40])

print("original series:")
print(s)

print("Addition:")
print(s+5)

print("subtraction:")
print(s-5)

print("multiplication:")
print(s*2)


print("division:")
print(s/2)

print("floor division:")
print(s // 3)

print("modulus:")
print(s % 3)

print("power:")
print(s ** 2)

original series:
0    10
1    20
2    30
3    40
dtype: int64
Addition:
0    15
1    25
2    35
3    45
dtype: int64
subtraction:
0     5
1    15
2    25
3    35
dtype: int64
multiplication:
0    20
1    40
2    60
3    80
dtype: int64
division:
0     5.0
1    10.0
2    15.0
3    20.0
dtype: float64
floor division:
0     3
1     6
2    10
3    13
dtype: int64
modulus:
0    1
1    2
2    0
3    1
dtype: int64
power:
0     100
1     400
2     900
3    1600
dtype: int64

### Q5. Find mean, min, max of a Series.
> 💡 **Hint:** Use `.mean()`, `.min()`, `.max()`, `.sum()`, `.median()`, `.std()` directly on the Series.

In [21]:
s = pd.Series([10,20,30,40])
print("mean:",s.mean())
print("min:",s.min())
print("max:",s.max())
print("sum:",s.sum())
print("median:",s.median())
print("std:",s.std())

mean: 25.0
min: 10
max: 40
sum: 100
median: 25.0
std: 12.909944487358056

### Q6. Apply conditional filtering on a Series.
> 💡 **Hint:** Use a boolean mask: `s[s > 50]`. You can also chain conditions with `&` and `|

In [27]:
s = pd.Series([15,35,65,20,40])

print(s[s>20])
print(s[(s > 20) & (s < 60)])
print(s[(s < 20) | (s >50)])

1    35
2    65
4    40
dtype: int64
1    35
4    40
dtype: int64
0    15
2    65
dtype: int64

### Q7. Replace values in a Series.
> 💡 **Hint:** Use `.replace(old_val, new_val)` or pass a dictionary `{old: new}` to replace multiple values at once.

In [31]:
s = pd.Series([10,20,30,40,50])
new = s.replace(20,99)

print(new)

new2 = s.replace({
    10:100,
    20:200,
    40:400
})
print(new2)

0    10
1    99
2    30
3    40
4    50
dtype: int64
0    100
1    200
2     30
3    400
4     50
dtype: int64

### Q8. Convert Series data type.
> 💡 **Hint:** Use `.astype(dtype)` — e.g., `.astype(int)`, `.astype(float)`, `.astype("category")`.

In [37]:
s = pd.Series([10.5,20.8,30])
print(s.dtype)
print(s.astype(int))
print(s.astype(float))
print(s.astype("category"))

float64
0    10
1    20
2    30
dtype: int64
0    10.5
1    20.8
2    30.0
dtype: float64
0    10.5
1    20.8
2    30.0
dtype: category
Categories (3, float64): [10.5, 20.8, 30.0]


### Q9. Check for null values in Series.
> 💡 **Hint:** Use `.isnull()` (returns boolean Series) or `.isnull().sum()` for a count.

In [43]:
import numpy as np
import pandas as pd
s = pd.Series([10,np.nan,20,30,np.nan])

print(s.isnull())
print(s.isnull().sum())

0    False
1     True
2    False
3    False
4     True
dtype: bool
2

### Q10. Fill missing values in Series.
> 💡 **Hint:** Use `.fillna(value)` for constant, `.fillna(s.mean())` for mean, `.ffill()` for forward fill, `.bfill()` for backward fill.

In [50]:
s = pd.Series([10,np.nan,30,40,np.nan,50])

print(s)
s.fillna(0)
s.fillna(s.mean())
s.ffill()
s.bfill()

0    10.0
1     NaN
2    30.0
3    40.0
4     NaN
5    50.0
dtype: float64

0    10.0
1    30.0
2    30.0
3    40.0
4    50.0
5    50.0
dtype: float64

### Q11. Create DataFrame from a list.
> 💡 **Hint:** Use `pd.DataFrame(list_of_lists, columns=[...])`. Each inner list becomes one row.

In [52]:
df = pd.DataFrame(
    [['John',25],['Mary',30]],
    columns=['Name','Age']
)
print(df)

   Name  Age
0  John   25
1  Mary   30

### Q12. Create DataFrame from a dictionary.
> 💡 **Hint:** Use `pd.DataFrame({col: values})`. Keys become column names; values must have equal length.

In [53]:
df = pd.DataFrame([
    {'Name':'Alice','Age':23},
    {'Name':'Bob','Age':34}
])
print(df)

    Name  Age
0  Alice   23
1    Bob   34

### Q13. Create DataFrame from list of dictionaries.
> 💡 **Hint:** Use `pd.DataFrame([{...}, {...}])`. Each dict is a row; missing keys become `NaN`.

In [55]:
df = pd.DataFrame([
    {'Name':'Alice','Age':23,'country':'UK'},
    {'Name':'Bob','country':'USA'},
    {'Name':'John','Age':25,'country':'Japan'}
])
print(df)

    Name   Age country
0  Alice  23.0      UK
1    Bob   NaN     USA
2   John  25.0   Japan

### Q14. Display DataFrame structure (shape, columns, dtypes).
> 💡 **Hint:** Use `df.shape`, `df.columns`, `df.dtypes`, `df.info()`, and `df.describe()`.

In [57]:
df = pd.DataFrame([
    {'Name':'Alice','Age':23},
    {'Name':'Bob','Age':34}
])
print(df)
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.info())
print(df.describe())

    Name  Age
0  Alice   23
1    Bob   34
(2, 2)
Index(['Name', 'Age'], dtype='str')
Name      str
Age     int64
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes
None
             Age
count   2.000000
mean   28.500000
std     7.778175
min    23.000000
25%    25.750000
50%    28.500000
75%    31.250000
max    34.000000

### Q15. Select single column from DataFrame.
> 💡 **Hint:** Use `df["col_name"]` — this returns a **Series**. You can also use `df.col_name` (dot notation)

In [60]:
df = pd.DataFrame([
    {'Name':'Alice','Age':23},
    {'Name':'Bob','Age':34}
])
df['Name']
df.Age

0    23
1    34
Name: Age, dtype: int64

### Q16. Select multiple columns.
> 💡 **Hint:** Use `df[["col1", "col2"]]` with a list inside the brackets — this returns a **DataFrame**.

In [62]:
df = pd.DataFrame([
    {'Name':'Alice','Age':23,'country':'UK','salary':40000},
    {'Name':'Bob','Age':20,'country':'USA','salary':50000},
    {'Name':'John','Age':25,'country':'Japan','salary':60000
     }
])
print(df)
df[['Name','country']]

    Name  Age country  salary
0  Alice   23      UK   40000
1    Bob   20     USA   50000
2   John   25   Japan   60000

    Name country
0  Alice      UK
1    Bob     USA
2   John   Japan

### Q17. Add new column with scalar value.
> 💡 **Hint:** `df["new_col"] = 10` — the scalar is **broadcast** to all rows automatically

In [65]:
df = pd.DataFrame([
    {'Name':'Alice','Age':23,'country':'UK','salary':40000},
    {'Name':'Bob','Age':20,'country':'USA','salary':50000},
    {'Name':'John','Age':25,'country':'Japan','salary':60000
     }
])
print(df)
df['score'] = 10
print(df)

    Name  Age country  salary
0  Alice   23      UK   40000
1    Bob   20     USA   50000
2   John   25   Japan   60000
    Name  Age country  salary  score
0  Alice   23      UK   40000     10
1    Bob   20     USA   50000     10
2   John   25   Japan   60000     10

### Q18. Add column using Series.
> 💡 **Hint:** `df["new_col"] = pd.Series([...])`. The Series index must align with the DataFrame index.

In [69]:
df = pd.DataFrame([
    {'Name':'Alice','Age':23,'country':'UK','salary':40000},
    {'Name':'Bob','Age':20,'country':'USA','salary':50000},
    {'Name':'John','Age':25,'country':'Japan','salary':60000
     }
])
print(df)
df['score']=pd.Series([10,15,12])
print(df)

    Name  Age country  salary
0  Alice   23      UK   40000
1    Bob   20     USA   50000
2   John   25   Japan   60000
    Name  Age country  salary  score
0  Alice   23      UK   40000     10
1    Bob   20     USA   50000     15
2   John   25   Japan   60000     12

### Q19. Rename columns using `rename()`.
> 💡 **Hint:** Use `df.rename(columns={"old": "new"})`. Add `inplace=True` to modify in-place.

In [76]:
df = pd.DataFrame([
    {'Name':'Alice','Age':23,'country':'UK','salary':40000},
    {'Name':'Bob','Age':20,'country':'USA','salary':50000},
    {'Name':'John','Age':25,'country':'Japan','salary':60000
     }
])
print(df)
df.rename(columns={'salary':'monthly_earning'},inplace = True)
print(df)

    Name  Age country  salary
0  Alice   23      UK   40000
1    Bob   20     USA   50000
2   John   25   Japan   60000
    Name  Age country  monthly_earning
0  Alice   23      UK            40000
1    Bob   20     USA            50000
2   John   25   Japan            60000

### Q20. Rename multiple columns.
> 💡 **Hint:** Pass a dictionary with multiple key-value pairs to `rename(columns={...})`.

In [78]:
df = pd.DataFrame([
    {'Name':'Alice','Age':23,'country':'UK','salary':40000},
    {'Name':'Bob','Age':20,'country':'USA','salary':50000},
    {'Name':'John','Age':25,'country':'Japan','salary':60000
     }
])

df.rename(columns={'Age':'employee_age','Name':'employee_name'},inplace=True)
print(df)

  employee_name  employee_age country  salary
0         Alice            23      UK   40000
1           Bob            20     USA   50000
2          John            25   Japan   60000

### Q21. Select rows using `loc`.
> 💡 **Hint:** `df.loc[label]` for a single row, `df.loc[label1:label2]` for a range. **Inclusive on both ends.**

In [85]:
employees = pd.DataFrame({
    'Name':['John','Mary','Alice','Bob'],
    'Department':['IT','HR','IT','Finance'],
    'Salary':[50000,60000,55000,70000]
}, index=['E1','E2','E3','E4'])

print(employees)
print(employees.loc['E1'])

print(employees.loc['E1':'E3'])

     Name Department  Salary
E1   John         IT   50000
E2   Mary         HR   60000
E3  Alice         IT   55000
E4    Bob    Finance   70000
Name           John
Department       IT
Salary        50000
Name: E1, dtype: object
     Name Department  Salary
E1   John         IT   50000
E2   Mary         HR   60000
E3  Alice         IT   55000


### Q22. Select rows using `iloc`.
> 💡 **Hint:** `df.iloc[0]` for first row, `df.iloc[1:4]` for rows 1–3. **Exclusive on the end** (Python-style).

In [87]:
employees = pd.DataFrame({
    'Name':['John','Mary','Alice','Bob'],
    'Department':['IT','HR','IT','Finance'],
    'Salary':[50000,60000,55000,70000]
}, index=['E1','E2','E3','E4'])

print(employees)
print(employees.iloc[0])
print(employees.iloc[0:2])

     Name Department  Salary
E1   John         IT   50000
E2   Mary         HR   60000
E3  Alice         IT   55000
E4    Bob    Finance   70000
Name           John
Department       IT
Salary        50000
Name: E1, dtype: object
    Name Department  Salary
E1  John         IT   50000
E2  Mary         HR   60000

### Q23. Access specific row and column.
> 💡 **Hint:** `df.loc[row_label, "col_name"]` or `df.iloc[row_pos, col_pos]` for a single cell.

In [92]:
employees = pd.DataFrame({
    'Name':['John','Mary','Alice','Bob'],
    'Department':['IT','HR','IT','Finance'],
    'Salary':[50000,60000,55000,70000]
}, index=['E1','E2','E3','E4'])

print(employees)
print(employees.loc['E1','Name'])
print(employees.iloc[0:2,0:2])

     Name Department  Salary
E1   John         IT   50000
E2   Mary         HR   60000
E3  Alice         IT   55000
E4    Bob    Finance   70000
John
    Name Department
E1  John         IT
E2  Mary         HR

### Q24. Select subset using multiple rows & columns.
> 💡 **Hint:** `df.loc[[r1,r2], ["col1","col2"]]` or `df.iloc[[0,1], [0,2]]`.

In [97]:
employees = pd.DataFrame({
    'Name':['John','Mary','Alice','Bob'],
    'Department':['IT','HR','IT','Finance'],
    'Salary':[50000,60000,55000,70000]
}, index=['E1','E2','E3','E4'])

print(employees.loc[['E1','E2'],['Name','Department']])

print(employees.iloc[[0,1],[0,1]])

    Name Department
E1  John         IT
E2  Mary         HR
    Name Department
E1  John         IT
E2  Mary         HR

### Q25. Apply conditional filtering using `loc`.
> 💡 **Hint:** `df.loc[df["col"] > value, ["col1","col2"]]` — pass a boolean Series as the row selector.

In [100]:
print(employees.loc[employees['Salary'] > 50000,['Name','Department']])

     Name Department
E2   Mary         HR
E3  Alice         IT
E4    Bob    Finance

### Q26. Slice rows using index range.
> 💡 **Hint:** Use `df.iloc[start:end]` for position-based slicing or `df.loc[label1:label2]` for label-based slicing.

In [105]:
print(employees.iloc[0:2])
print(employees.loc['E1':'E3'])

    Name Department  Salary
E1  John         IT   50000
E2  Mary         HR   60000
     Name Department  Salary
E1   John         IT   50000
E2   Mary         HR   60000
E3  Alice         IT   55000

### Q27. Slice columns using labels.
> 💡 **Hint:** `df.loc[:, "col1":"col3"]` — selects all rows, columns from col1 to col3 (label-inclusive).

In [110]:
print(employees.loc[:,'Name':'Salary'])

     Name Department  Salary
E1   John         IT   50000
E2   Mary         HR   60000
E3  Alice         IT   55000
E4    Bob    Finance   70000

### Q28. Slice columns using position.
> 💡 **Hint:** `df.iloc[:, 1:4]` — selects all rows, columns at positions 1, 2, 3.

In [115]:
print(employees.iloc[:,0:3])

     Name Department  Salary
E1   John         IT   50000
E2   Mary         HR   60000
E3  Alice         IT   55000
E4    Bob    Finance   70000

### Q29. Perform combined row & column slicing.
> 💡 **Hint:** `df.loc[row_condition, ["col1","col2"]]` or `df.iloc[0:5, [0, 2, 4]]`.

In [ ]:
#print(employees.loc[employees['Salary'] > 50000,['Name']])

print(employees.iloc[0:3,[0,2,1]])

     Name  Salary Department
E1   John   50000         IT
E2   Mary   60000         HR
E3  Alice   55000         IT

### Q30. Set a column as index.
> 💡 **Hint:** Use `df.set_index("col_name")`. Add `inplace=True` to modify without reassigning.

In [127]:
df = pd.DataFrame({
    'Id':[101,102,103],
    'Name':['John','Alice','Mary'],
    'Age':[24,23,22]
})
print(df)
df.set_index('Id',inplace = True)
print(df)

    Id   Name  Age
0  101   John   24
1  102  Alice   23
2  103   Mary   22
      Name  Age
Id
101   John   24
102  Alice   23
103   Mary   22

### Q31. Create hierarchical index (MultiIndex).
> 💡 **Hint:** `df.set_index(["col1","col2"])` — pass a **list** of column names to create a MultiIndex.

In [130]:
df = pd.DataFrame({
    'Id':[101,102,103],
    'Name':['John','Alice','Mary'],
    'Age':[24,23,22]
})
print(df)
print(df.set_index(['Id','Name']))

    Id   Name  Age
0  101   John   24
1  102  Alice   23
2  103   Mary   22
           Age
Id  Name
101 John    24
102 Alice   23
103 Mary    22

### Q32. Reset index.
> 💡 **Hint:** `df.reset_index()` — moves the current index back to a column. Use `inplace=True` to modify in-place.

In [4]:
import pandas as pd
df = pd.DataFrame({
    'Id':[101,102,103],
    'Name':['John','Alice','Mary'],
    'Age':[24,23,22]
},index=['r0','r1','r2'])
print(df)
df.reset_index(inplace=True)
print(df)

     Id   Name  Age
r0  101   John   24
r1  102  Alice   23
r2  103   Mary   22
  index   Id   Name  Age
0    r0  101   John   24
1    r1  102  Alice   23
2    r2  103   Mary   22

### Q33. Reset multi-index.
> 💡 **Hint:** `df.reset_index()` on a MultiIndex DataFrame flattens both index levels back to columns

In [8]:
df = pd.DataFrame({
    'Id':[101,102,103],
    'Name':['John','Alice','Mary'],
    'Age':[24,23,22]
})
print(df)
df_multi = df.set_index(['Id','Name'])
print(df_multi)

print(df_multi.reset_index())

    Id   Name  Age
0  101   John   24
1  102  Alice   23
2  103   Mary   22
           Age
Id  Name
101 John    24
102 Alice   23
103 Mary    22
    Id   Name  Age
0  101   John   24
1  102  Alice   23
2  103   Mary   22

### Q34. Convert index to column.
> 💡 **Hint:** `df.reset_index()` by default moves the index to a column. Use `drop=False` (default) to keep it.

In [12]:
df = pd.DataFrame({
    'Id':[101,102,103],
    'Name':['John','Alice','Mary'],
    'Age':[24,23,22]
})

df_multi = df.set_index(['Id','Name'])
print(df_multi)
print(df_multi.reset_index(drop=False))

           Age
Id  Name
101 John    24
102 Alice   23
103 Mary    22
    Id   Name  Age
0  101   John   24
1  102  Alice   23
2  103   Mary   22


### Q35. Use drop option in `reset_index`.
> 💡 **Hint:** `df.reset_index(drop=True)` discards the old index completely instead of converting it to a column.

In [13]:
df = pd.DataFrame({
    'Id':[101,102,103],
    'Name':['John','Alice','Mary'],
    'Age':[24,23,22]
})

df_multi = df.set_index(['Id','Name'])
print(df_multi)
print(df_multi.reset_index(drop=True))

           Age
Id  Name
101 John    24
102 Alice   23
103 Mary    22
   Age
0   24
1   23
2   22

### Q36. Perform label-based indexing.
> 💡 **Hint:** Use `df.loc[label]` — works with any index type (string, integer, datetime labels).

In [20]:
df = pd.DataFrame({
    'age':[24,23,22],
    'city':['London','Paris','Rome']
},index = ['john','Alice','mary'])
print(df)

df.loc['mary']

       age    city
john    24  London
Alice   23   Paris
mary    22    Rome

age       22
city    Rome
Name: mary, dtype: object

### Q37. Perform position-based indexing.
> 💡 **Hint:** Use `df.iloc[0]` — always integer-based, regardless of the index type.

In [24]:
df = pd.DataFrame({
    'name':['john','mary','alice'],
    'age':[24,23,22],
    'city':['London','Paris','Rome']
})
print(df)
df.iloc[0]

    name  age    city
0   john   24  London
1   mary   23   Paris
2  alice   22    Rome

name      john
age         24
city    London
Name: 0, dtype: object

### Q38. Access first N rows.
> 💡 **Hint:** `df.head(N)` — default N is 5.

In [28]:

df = pd.DataFrame({
    'Name': ['John', 'Alice', 'Mary', 'Bob', 'Tom', 'Emma'],
    'Age': [24, 23, 22, 25, 21, 26]
})

print(df.head())

    Name  Age
0   John   24
1  Alice   23
2   Mary   22
3    Bob   25
4    Tom   21

### Q39. Access last N rows.
> 💡 **Hint:** `df.tail(N)` — default N is 5.

In [29]:
print(df.tail())

    Name  Age
1  Alice   23
2   Mary   22
3    Bob   25
4    Tom   21
5   Emma   26

### Q40. Extract random sample from DataFrame.
> 💡 **Hint:** `df.sample(n=5)` for random rows, `df.sample(frac=0.2)` for 20% of rows. Set `random_state` for reproducibility.

In [34]:
df = pd.DataFrame({
    'Name': ['John', 'Alice', 'Mary', 'Bob', 'Tom', 'Emma'],
    'Age': [24, 23, 22, 25, 21, 26]
})

print(df.sample(n=5))

   Name  Age
3   Bob   25
4   Tom   21
2  Mary   22
0  John   24
5  Emma   26

In [35]:
print(df.sample(frac=0.2))

  Name  Age
3  Bob   25

In [39]:
print(df.sample(n=3,random_state=42))

    Name  Age
0   John   24
1  Alice   23
5   Emma   26

### Q41. Detect missing values using `isnull()`.
> 💡 **Hint:** `df.isnull()` returns a boolean DataFrame. Use `.isnull().sum()` for column-wise counts or `.isnull().any()` to check if any exist.

In [6]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    'name':['john','alice',None],
    'age':[24,np.nan,30],
    'city':['london','paris',None]
})
df.isnull()
df.isnull().sum()
df.isnull().any()

name    True
age     True
city    True
dtype: bool

### Q42. Drop missing values using `dropna()`.
> 💡 **Hint:** `df.dropna()` drops any row with a NaN. Use `axis=1` for columns, `subset=["col"]` for specific columns, and `thresh=N` to keep rows with at least N non-null values.

In [14]:
df = pd.DataFrame({
    'name':['john','alice',None],
    'age':[24,np.nan,30],
    'city':['london','paris',None]
})
#print(df)

df2 = df.dropna()
print(df2)

   name   age    city
0  john  24.0  london

In [11]:

df2 = df.dropna(axis=1)
print(df2)

Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [12]:
df2 = df.dropna(subset=['age'])
print(df2)

   name   age    city
0  john  24.0  london
2   NaN  30.0     NaN

In [13]:

df2 = df.dropna(thresh=2)
print(df2)

    name   age    city
0   john  24.0  london
1  alice   NaN   paris

### Q43. Fill missing values with a constant.
> 💡 **Hint:** `df.fillna(0)` or `df["col"].fillna("Unknown")`. You can also pass a dict to fill different columns with different values.

In [16]:
df = pd.DataFrame({
    'name':['john','alice',None],
    'age':[24,np.nan,30],
    'city':['london','paris',None]
})

df2 = df.fillna(0)
print(df2)

    name   age    city
0   john  24.0  london
1  alice   0.0   paris
2      0  30.0       0

In [17]:
df['name'] = df['name'].fillna("unknown")
print(df)

      name   age    city
0     john  24.0  london
1    alice   NaN   paris
2  unknown  30.0     NaN

In [18]:
df = df.fillna({
    'age':0,
    'city':'unknown'
})
print(df)

      name   age     city
0     john  24.0   london
1    alice   0.0    paris
2  unknown  30.0  unknown

### Q44. Fill missing values using mean/median.
> 💡 **Hint:** `df["col"].fillna(df["col"].mean())` or `df["col"].fillna(df["col"].median())`.

In [20]:
df = pd.DataFrame({
    'age':[24,np.nan,30,26,np.nan]
})

df2 = df['age'].fillna(df['age'].mean())
print(df2)

df3 =  df['age'].fillna(df['age'].median())
print(df2)

0    24.000000
1    26.666667
2    30.000000
3    26.000000
4    26.666667
Name: age, dtype: float64
0    24.000000
1    26.666667
2    30.000000
3    26.000000
4    26.666667
Name: age, dtype: float64

### Q45. Use forward fill and backward fill.
> 💡 **Hint:** `df.ffill()` propagates the last valid value forward. `df.bfill()` fills using the next valid value.

In [22]:
df = pd.DataFrame({
    'age':[24,np.nan,30,26,np.nan]
})

df.ffill()
df.bfill()

    age
0  24.0
1  30.0
2  30.0
3  26.0
4   NaN


### Q46. Convert data type using `astype()`.
> 💡 **Hint:** `df["col"].astype(int)` or `df["col"].astype("category")`. Use `errors="coerce"` inside `pd.to_numeric()` to handle invalid values.

In [26]:
df = pd.DataFrame({
    'age':['24','30','28']
})
print(df.dtypes)

df['age'] = df['age'].astype(int)
print(df)
print(df.dtypes)

age    str
dtype: object
   age
0   24
1   30
2   28
age    int64
dtype: object

In [31]:
df = pd.DataFrame({
    'city':['london','paris','london','berlin']
})

df['city'] = df['city'].astype("category")
print(df.dtypes)

city    category
dtype: object

In [27]:
df = pd.DataFrame({
    'age':['24','30','abc','28']
})
df['age'] = pd.to_numeric(df['age'],errors='coerce')

print(df)

    age
0  24.0
1  30.0
2   NaN
3  28.0

### Q47. Clean string column using `.str.lower()`.
> 💡 **Hint:** Access the `.str` accessor first: `df["col"].str.lower()`. Similarly `.str.upper()`, `.str.title()`.

In [35]:
df = pd.DataFrame({
    'CITY':['London','berlin','PARIS','uK']
})

df['CITY'].str.lower()
df['CITY'].str.upper()
df['CITY'].str.title()

0    London
1    Berlin
2     Paris
3        Uk
Name: CITY, dtype: str


### Q48. Trim whitespace in strings.
> 💡 **Hint:** `df["col"].str.strip()` removes leading and trailing spaces. Use `.str.lstrip()` / `.str.rstrip()` for one side.

In [50]:
df = pd.DataFrame({
    'name':[' john ',' alice','mary ']
})
df['name'] = df['name'].str.strip()
print(df)

df['name'].str.lstrip()
df['name'] = df['name'].str.rstrip()
print(df)

    name
0   john
1  alice
2   mary
    name
0   john
1  alice
2   mary


### Q49. Replace substring in column.
> 💡 **Hint:** `df["col"].str.replace("old", "new")`. Add `regex=True` for pattern-based replacement.

In [52]:
df = pd.DataFrame({
    'city':['new york','new delhi','new jersey']
})

print(df)
df['city'].str.replace("new","old")

         city
0    new york
1   new delhi
2  new jersey

0      old york
1     old delhi
2    old jersey
Name: city, dtype: str

In [54]:
s = pd.Series(['john123','alice345'])
print(s.str.replace(r'\d+','',regex=True))

0     john
1    alice
dtype: str

### Q50. Extract part of string using `.str`.
> 💡 **Hint:** `df["col"].str[:3]` for first 3 chars. Use `.str.split("@").str[1]` to extract after a delimiter.

In [56]:
df = pd.DataFrame({
    'name':['john','alice','mary']
})
df['name'].str[:3]
df['name'].str[-2:]

0    hn
1    ce
2    ry
Name: name, dtype: str

In [58]:
df = pd.DataFrame({
    'email':['john@gmail.com','alice@gmail.com']
})
df['email'].str.split("@").str[1]

0    gmail.com
1    gmail.com
Name: email, dtype: object

### Q51. Detect duplicate rows.
> 💡 **Hint:** `df.duplicated()` returns a boolean Series. Use `df[df.duplicated()]` to see the actual duplicate rows.

In [61]:
df = pd.DataFrame({
    "Name": ["John", "Alice", "John", "Mary"],
    "Age": [24, 30, 24, 28]
})

print(df)
print(df.duplicated())
print(df[df.duplicated()])

    Name  Age
0   John   24
1  Alice   30
2   John   24
3   Mary   28
0    False
1    False
2     True
3    False
dtype: bool
   Name  Age
2  John   24

### Q52. Remove duplicates using `drop_duplicates()`.
> 💡 **Hint:** `df.drop_duplicates()` keeps the first occurrence by default. Use `subset=["col"]` to check specific columns, and `keep="last"` or `keep=False`.

In [72]:
df = pd.DataFrame({
    "Name": ["John", "Alice", "John", "Mary"],
    "Age": [24, 30, 24, 28]
})

#print(df)
df2 = df.drop_duplicates()
print(df2)

    Name  Age
0   John   24
1  Alice   30
3   Mary   28

In [73]:
df3 = df.drop_duplicates(subset=['Name'])
print(df3)

    Name  Age
0   John   24
1  Alice   30
3   Mary   28

In [74]:
df4 = df.drop_duplicates(subset=['Name'],keep = 'last')
print(df4)

    Name  Age
1  Alice   30
2   John   24
3   Mary   28

In [75]:
df5 = df.drop_duplicates(subset=['Name'],keep = False)
print(df5)

    Name  Age
1  Alice   30
3   Mary   28

In [76]:
df.drop_duplicates(inplace=True)

In [77]:
print(df)

    Name  Age
0   John   24
1  Alice   30
3   Mary   28

### Q53. Rename row labels.
> 💡 **Hint:** `df.rename(index={old_label: new_label})`.

In [82]:

df = pd.DataFrame({
    "Name": ["John", "Alice", "Mary"],
    "Age": [24, 30, 28]
})
print(df)

df.rename(index={0:'A',1:'B'},inplace=True)
print(df)

    Name  Age
0   John   24
1  Alice   30
2   Mary   28
    Name  Age
A   John   24
B  Alice   30
2   Mary   28

### Q54. Handle inconsistent data.
> 💡 **Hint:** Use `.str.strip().str.lower()` to normalize strings. Use `.replace({...})` to map inconsistent values to a standard form.

In [84]:
df = pd.DataFrame({
    "Country": ["USA", "usa", " U.S.A. ", "India", "INDIA"]
})

print(df)

df['Country'] = df['Country'].str.strip().str.lower()
print(df)

    Country
0       USA
1       usa
2   U.S.A.
3     India
4     INDIA
  Country
0     usa
1     usa
2  u.s.a.
3   india
4   india

In [86]:
df['Country'] = df['Country'].replace({
    'u.s.a.':'usa',
    'united states':'usa'
})
print(df)

  Country
0     usa
1     usa
2     usa
3   india
4   india

In [88]:
df = pd.DataFrame({
    "Gender": ["M", "Male", "male", "F", "Female"]
})

df['Gender']=df['Gender'].str.strip().str.lower().replace({
    "m":"male",
    "f":"female"
})
print(df)

   Gender
0    male
1    male
2    male
3  female
4  female


### Q55. Replace values in DataFrame.
> 💡 **Hint:** `df.replace("old", "new")` works DataFrame-wide. Pass a dict `{old: new}` or nested dict `{"col": {old: new}}` for column-specific replacement.

In [91]:
df = pd.DataFrame({
    "Name": ["John", "Alice", "John"],
    "City": ["London", "Paris", "London"]
})

print(df)
df2 = df.replace('John','Jonny')
print(df2)

    Name    City
0   John  London
1  Alice   Paris
2   John  London
    Name    City
0  Jonny  London
1  Alice   Paris
2  Jonny  London

In [92]:
df2 = df.replace({
    'John':'Jonny',
    'Paris':'Berlin'
})
print(df2)

    Name    City
0  Jonny  London
1  Alice  Berlin
2  Jonny  London

In [93]:
df2 = df.replace({
    'City':{
        'London':'LON',
        'Paris':'PAR'
    }
})
print(df2)

    Name City
0   John  LON
1  Alice  PAR
2   John  LON


### Q56. Detect outliers in a column.
> 💡 **Hint:** Use the **IQR method**: compute Q1, Q3, IQR = Q3–Q1. Outliers are values below `Q1 - 1.5*IQR` or above `Q3 + 1.5*IQR`. Alternatively use Z-score: `|z| > 3`.

In [95]:
df = pd.DataFrame({
    'salary':[30,35,40,45,50,55,200]
})

q1 = df['salary'].quantile(0.25)
q3 = df['salary'].quantile(0.75)

iqr = q3 - q1

lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr

print(lower,upper)

ouliers = df[(df['salary'] < lower) | (df['salary'] > upper)]

print(ouliers)

15.0 75.0
   salary
6     200

### Q57. Handle outliers using clipping.
> 💡 **Hint:** `df["col"].clip(lower=lo, upper=hi)` replaces values outside the bounds with the boundary values.

In [96]:
df['salary'] = df['salary'].clip(lower=30,upper=60)
print(df)

   salary
0      30
1      35
2      40
3      45
4      50
5      55
6      60

### Q58. Standardize column names.
> 💡 **Hint:** `df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")` — clean all column names in one line.

In [99]:
df = pd.DataFrame({
    " First Name ": ["John", "Alice"],
    "Last Name": ["Doe", "Smith"],
    "Employee ID": [101, 102]
})

print(df.columns)

df.columns = df.columns.str.strip().str.lower().str.replace(" ","_")
print(df.columns)

Index([' First Name ', 'Last Name', 'Employee ID'], dtype='str')
Index(['first_name', 'last_name', 'employee_id'], dtype='str')

### Q59. Handle mixed data types in a column.
> 💡 **Hint:** Use `pd.to_numeric(df["col"], errors="coerce")` to convert to numbers, turning invalid strings into `NaN`.

In [100]:
df = pd.DataFrame({
    'values':[12,24,23,'abc',34,34,'mno']
})

df['values'] = pd.to_numeric(df['values'],errors='coerce')
print(df)

   values
0    12.0
1    24.0
2    23.0
3     NaN
4    34.0
5    34.0
6     NaN

### Q60. Remove special characters from text data.
> 💡 **Hint:** `df["col"].str.replace(r"[^a-zA-Z0-9 ]", "", regex=True)` — use regex to keep only alphanumeric characters.

In [102]:
df = pd.DataFrame({
    "Text": ["Hello@123!", "Python#Data$", "AI & ML"]
})

print(df)

df['Text'] = df['Text'].str.replace(r"[^a-zA-Z0-9]","",regex=True)
print(df)

           Text
0    Hello@123!
1  Python#Data$
2       AI & ML
         Text
0    Hello123
1  PythonData
2        AIML


### Q61. Filter rows using AND condition.
> 💡 **Hint:** `df[(df["col1"] > val) & (df["col2"] == "x")]` — wrap each condition in parentheses and use `&`.

In [2]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "Name": ["John", "Alice", "Mary", "Bob"],
    "Age": [24, 32, 25, 40],
    "Country": ["UK", "UK", "US", "UK"]
})
result = df[(df['Age'] > 25) & (df['Country'] == 'UK')]
print(result)

    Name  Age Country
1  Alice   32      UK
3    Bob   40      UK

### Q62. Filter rows using OR condition.
> 💡 **Hint:** `df[(df["col1"] > val) | (df["col2"] == "x")]` — use `|` between conditions.

In [3]:
df = pd.DataFrame({
    "Name": ["John", "Alice", "Mary", "Bob"],
    "Age": [24, 32, 25, 40],
    "Country": ["UK", "UK", "US", "UK"]
})
result = df[(df['Age'] > 25) | (df['Country'] == 'UK')]
print(result)

    Name  Age Country
0   John   24      UK
1  Alice   32      UK
3    Bob   40      UK

### Q63. Filter rows using NOT condition.
> 💡 **Hint:** `df[~(df["col"] == "val")]` — use `~` to negate a boolean condition.

In [5]:
df = pd.DataFrame({
    "Name": ["John", "Alice", "Mary", "Bob"],
    "Age": [24, 32, 25, 40],
    "Country": ["UK", "UK", "US", "UK"]
})
df[~(df['Country'] == 'UK')]

   Name  Age Country
2  Mary   25      US

### Q64. Sort DataFrame by column values.
> 💡 **Hint:** `df.sort_values("col")`. Use `ascending=False` for descending, `by=["col1","col2"]` for multi-column sort.

In [9]:
df = pd.DataFrame({
    "Name": ["John", "Alice", "Mary", "Bob"],
    "Age": [24, 32, 25, 40]
})

result = df.sort_values("Age")
print(result)

result2 = df.sort_values("Age",ascending=False)
print(result2)

result3 = df.sort_values(by=['Name','Age'])
print(result3)

    Name  Age
0   John   24
2   Mary   25
1  Alice   32
3    Bob   40
    Name  Age
3    Bob   40
1  Alice   32
2   Mary   25
0   John   24
    Name  Age
1  Alice   32
3    Bob   40
0   John   24
2   Mary   25


### Q65. Sort DataFrame by index.
> 💡 **Hint:** `df.sort_index()`. Use `axis=1` to sort columns alphabetically.

In [21]:
df = pd.DataFrame({
    "Name": ["John", "Alice", "Mary"],
    'Age':[24,32,25]
}, index=[2, 0, 1])
print(df)

#print(df.sort_index())
print(df.sort_index(axis=1))

    Name  Age
2   John   24
0  Alice   32
1   Mary   25
   Age   Name
2   24   John
0   32  Alice
1   25   Mary

### Q66. Add calculated column.
> 💡 **Hint:** `df["new"] = df["col1"] * df["col2"]` or use `.assign(new=lambda x: ...)` for chainable operations.

In [22]:
df = pd.DataFrame({
    "Price": [100, 200, 150],
    "Quantity": [2, 3, 4]
})

df['total'] = df['Price'] * df['Quantity']
print(df)

   Price  Quantity  total
0    100         2    200
1    200         3    600
2    150         4    600

In [24]:
df = df.assign(total = lambda x: x['Price'] * x['Quantity'])
print(df)

   Price  Quantity  total
0    100         2    200
1    200         3    600
2    150         4    600

### Q67. Remove column using `drop()`.
> 💡 **Hint:** `df.drop(columns=["col1","col2"])`. Always use the `columns=` parameter to be explicit.

In [26]:
df = pd.DataFrame({
    "Name": ["John", "Alice", "Mary"],
    "Age": [24, 32, 25],
    "Country": ["UK", "UK", "US"]
})

result = df.drop(columns=['Country','Age'])
print(result)

    Name
0   John
1  Alice
2   Mary


### Q68. Remove rows using `drop()`.
> 💡 **Hint:** `df.drop(index=[0, 3])` removes rows with those index labels.

In [29]:
df = pd.DataFrame({
    "Name": ["John", "Alice", "Mary"],
    "Age": [24, 32, 25],
    "Country": ["UK", "UK", "US"]
})
print(df)
df.drop(index=[0,1])

    Name  Age Country
0   John   24      UK
1  Alice   32      UK
2   Mary   25      US

   Name  Age Country
2  Mary   25      US


### Q69. Use `map()` on a column.
> 💡 **Hint:** `df["col"].map({"a": 1, "b": 2})` substitutes values using a dict. Pass a function for element-wise transformation.

In [34]:
df = pd.DataFrame({
    "Grade": ["A", "B", "A", "C",'D']
})
df['points'] = df['Grade'].map({
    'A':4,
    'B':3,
    'C':2
})
print(df)


df['points_using_replace'] = df['Grade'].replace({
    'A':4,
    'B':3,
    'C':2
})
print(df)

  Grade  points
0     A     4.0
1     B     3.0
2     A     4.0
3     C     2.0
4     D     NaN
  Grade  points points_using_replace
0     A     4.0                    4
1     B     3.0                    3
2     A     4.0                    4
3     C     2.0                    2
4     D     NaN                    D


### Q70. Apply function using `apply()`.
> 💡 **Hint:** `df["col"].apply(func)` for a Series. `df.apply(func, axis=0)` column-wise, `df.apply(func, axis=1)` row-wise.

In [41]:

df = pd.DataFrame({
    "Age": [20, 25, 30]
})

df['age+5'] = df['Age'].apply(lambda x:x+5)
print(df)

   Age  age+5
0   20     25
1   25     30
2   30     35

In [44]:
df = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [4, 5, 6]
})
print(df)
print(df.apply(sum,axis=0))
print(df.apply(sum,axis=1))

   A  B
0  1  4
1  2  5
2  3  6
A     6
B    15
dtype: int64
0    5
1    7
2    9
dtype: int64

### Q71. Apply element-wise using `applymap()` / `map()`.
> 💡 **Hint:** In older pandas use `df.applymap(func)`. In pandas ≥ 2.1 use `df.map(func)` for element-wise operations on the entire DataFrame.

In [ ]:
df = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [4, 5, 6]
})
print(df)
result = df.map(lambda x:x * 10)
print(result)

   A  B
0  1  4
1  2  5
2  3  6
A     6
B    15
dtype: int64
    A   B
0  10  40
1  20  50
2  30  60

### Q72. Chain multiple operations.
> 💡 **Hint:** Use method chaining with `(df.copy().loc[...].sort_values(...)[cols].assign(...).reset_index(drop=True))` — wrap in parentheses for multi-line readability.

In [51]:

df = pd.DataFrame({
    "Name": ["John", "Alice", "Mary", "Bob"],
    "Age": [24, 32, 25, 40],
    "Salary": [50000, 70000, 60000, 80000]
})

result = (
    df.copy().loc[lambda x:x['Age'] >25]
    .sort_values('Salary',ascending=False)
    [['Name','Age','Salary']].assign(bonus = lambda x:x['Salary'] * 0.10)
    .reset_index(drop = True)
)
print(result)

    Name  Age  Salary   bonus
0    Bob   40   80000  8000.0
1  Alice   32   70000  7000.0

### Q73. Normalize numeric columns (Min-Max).
> 💡 **Hint:** `(df["col"] - df["col"].min()) / (df["col"].max() - df["col"].min())` — result is in range [0, 1].

In [52]:

df = pd.DataFrame({
    "Marks": [40, 60, 80, 100]
})
df['normalized'] = ((df['Marks'] - df['Marks'].min()) /
                    (df['Marks'].max() - df['Marks'].min()))
print(df)

   Marks  normalized
0     40    0.000000
1     60    0.333333
2     80    0.666667
3    100    1.000000

### Q74. Scale numerical data (Z-score standardization).
> 💡 **Hint:** `(df["col"] - df["col"].mean()) / df["col"].std()` — result has mean=0 and std=1.

In [54]:
df = pd.DataFrame({
    "Marks": [40, 60, 80, 100]
})

df['zscore'] = (df['Marks'] - df['Marks'].mean()) / df['Marks'].std()
print(df)
print(df['zscore'].mean())
print(df['zscore'].std())

   Marks    zscore
0     40 -1.161895
1     60 -0.387298
2     80  0.387298
3    100  1.161895
0.0
1.0

### Q75. Rank values in a column.
> 💡 **Hint:** `df["col"].rank()` — use `ascending=False` for descending rank, `method="dense"` to avoid gaps.

In [57]:
df = pd.DataFrame({
    "Score": [90, 75, 90, 60]
})

df['rank'] = df['Score'].rank()
print(df)


df['rank_as=fal'] = df['Score'].rank(ascending=False)
print(df)

df['rank_as=fal_dense'] = df['Score'].rank(ascending=False,method='dense')
print(df)

   Score  rank
0     90   3.5
1     75   2.0
2     90   3.5
3     60   1.0
   Score  rank  rank_as=fal
0     90   3.5          1.5
1     75   2.0          3.0
2     90   3.5          1.5
3     60   1.0          4.0
   Score  rank  rank_as=fal  rank_as=fal_dense
0     90   3.5          1.5                1.0
1     75   2.0          3.0                2.0
2     90   3.5          1.5                1.0
3     60   1.0          4.0                3.0

### Q76. Create bins using `cut()`.
> 💡 **Hint:** `pd.cut(df["col"], bins=4)` for equal-width bins or `pd.cut(df["col"], bins=[0,25,50,75,100], labels=["Low","Mid","High","Top"])` for custom intervals.

In [60]:
df = pd.DataFrame({
    "Marks": [10, 25, 40, 55, 70, 85, 100]
})

df['bins'] = pd.cut(df['Marks'],bins=4)
print(df)

df['Category'] = pd.cut(df['Marks'],bins = [0,25,50,75,100],labels = ['low','mid','high','top'])
print(df)

   Marks           bins
0     10   (9.91, 32.5]
1     25   (9.91, 32.5]
2     40   (32.5, 55.0]
3     55   (32.5, 55.0]
4     70   (55.0, 77.5]
5     85  (77.5, 100.0]
6    100  (77.5, 100.0]
   Marks           bins Category
0     10   (9.91, 32.5]      low
1     25   (9.91, 32.5]      low
2     40   (32.5, 55.0]      mid
3     55   (32.5, 55.0]     high
4     70   (55.0, 77.5]     high
5     85  (77.5, 100.0]      top
6    100  (77.5, 100.0]      top

### Q77. Create bins using `qcut()`.
> 💡 **Hint:** `pd.qcut(df["col"], q=4)` for **equal-frequency** (quantile-based) bins. Use `labels=["Q1","Q2","Q3","Q4"]` for named bins.

In [62]:
df = pd.DataFrame({
    "Marks": [10, 20, 30, 40, 50, 60, 70, 80]
})

df['Quantile'] = pd.qcut(df['Marks'],q=4,labels=['Q1','Q2','Q3','Q4'])
print(df)

   Marks Quantile
0     10       Q1
1     20       Q1
2     30       Q2
3     40       Q2
4     50       Q3
5     60       Q3
6     70       Q4
7     80       Q4

### Q78. Count unique values.
> 💡 **Hint:** `df["col"].nunique()` for the count, `df["col"].value_counts()` for frequency per unique value.

In [64]:
df = pd.DataFrame({
    "Country": ["UK", "US", "UK", "India", "US"]
})

print(df['Country'].nunique())
print(df['Country'].value_counts())

3
Country
UK       2
US       2
India    1
Name: count, dtype: int64

### Q79. Replace multiple values at once.
> 💡 **Hint:** `df.replace({"col": {"old1": "new1", "old2": "new2"}})` or use a list: `df.replace(["old1","old2"], "new")`.

In [65]:
df = pd.DataFrame({
    "Grade": ["A", "B", "C", "A"]
})
df = df.replace({
    'Grade':{
        'A':'Excellent',
        'B':'Good'
    }
})
print(df)

       Grade
0  Excellent
1       Good
2          C
3  Excellent

In [70]:
df1 = pd.DataFrame({
    "Status": ["Pending", "Waiting", "Done", "Pending"]
})
df1 = df1.replace(['Pending','Waiting'],'In progress')
print(df1)

        Status
0  In progress
1  In progress
2         Done
3  In progress

### Q80. Create flag column based on condition.
> 💡 **Hint:** `df["flag"] = (df["col"] > threshold).astype(int)` — converts True/False to 1/0. Or use `np.where(condition, 1, 0)`.

In [73]:
df = pd.DataFrame({
    "Marks": [35, 60, 45, 80,0]
})

df['flag'] =np.where(df['Marks'] >= 50,1,0).astype(int)
print(df)

   Marks  flag
0     35     0
1     60     1
2     45     0
3     80     1
4      0     0