In [98]:
import pandas as pd 
import numpy as np

In [99]:
# 1. Create a Series using a list of 5 numbers.

s1 = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
print(s1)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [100]:
# 1. Create a Series using a list of 5 numbers.
# 2. Create a Series using a dictionary of student marks.
# 3. Create a DataFrame using a list of dictionaries.
# 4. Add a new column using scalar values.
# 5. Add a new column using a Series.
# 6. Rename one column and multiple columns.
# 7. Use loc to select:
#    - A single row
#    - Multiple rows
#    - Conditional rows
# 8. Use iloc to select:
#    - First row
#    - Second column
#    - First three rows and two columns
# 9. Find DataFrame shape and dtypes.
# 10. Handle missing values using fillna().

In [101]:
# 2. Create a Series using a dictionary of student marks.
s2=pd.Series(
    {"english":85,"maths":44,"science":99}
)
print(s2)

english    85
maths      44
science    99
dtype: int64

In [102]:
# 3. Create a DataFrame using a list of dictionaries.

s3 = pd.DataFrame([

        {"hello":45,"vaishnavi":55},{"how are you ":45,"i am fine":44}
])
print(s3)

   hello  vaishnavi  how are you   i am fine
0   45.0       55.0           NaN        NaN
1    NaN        NaN          45.0       44.0

In [103]:
# 4. Add a new column using scalar values.

df = pd.DataFrame({
    'Name':['vaishnavi','EL','Alice'],
    'Age':[23,30,28]
})

df["country"]="india" # scalar wise 
print(df)

        Name  Age country
0  vaishnavi   23   india
1         EL   30   india
2      Alice   28   india

In [104]:
# 5. Add a new column using a Series.
new_clo_series=pd.Series([5,6,4])
df["new_cloumn_series"]=new_clo_series
print(df)

        Name  Age country  new_cloumn_series
0  vaishnavi   23   india                  5
1         EL   30   india                  6
2      Alice   28   india                  4

In [105]:
# 6. Rename one column and multiple columns.
df.rename(columns={'Age':'Employee_Age'}, inplace=True)
print(df)
df.rename(
    {
        "Name":"full_name",
        "Bonus":"update_bouns"
    },inplace=True
)
print(df)

        Name  Employee_Age country  new_cloumn_series
0  vaishnavi            23   india                  5
1         EL            30   india                  6
2      Alice            28   india                  4
        Name  Employee_Age country  new_cloumn_series
0  vaishnavi            23   india                  5
1         EL            30   india                  6
2      Alice            28   india                  4

In [106]:
# 7. Use loc to select:
#    - A single row
#    - Multiple rows
#    - Conditional rows

In [107]:
student = pd.DataFrame({
    'Name':['John','Mary','Alice','Bob'],
    'subject':["english","maths","science","hindi"],
    'fees':[50000,60000,55000,70000]
}, index=['E1','E2','E3','E4'])

print(student)

     Name  subject   fees
E1   John  english  50000
E2   Mary    maths  60000
E3  Alice  science  55000
E4    Bob    hindi  70000

In [108]:
student.loc['E1']
student.loc[['E1','E3'], ['Name','fees']]
student.loc[student['fees'] < 70000]

     Name  subject   fees
E1   John  english  50000
E2   Mary    maths  60000
E3  Alice  science  55000

In [109]:
# 8. Use iloc to select:
#    - First row
#    - Second column
#    - First three rows and two columns

In [110]:
student.iloc[0]

Name          John
subject    english
fees         50000
Name: E1, dtype: object

In [111]:
student.iloc[1]

Name        Mary
subject    maths
fees       60000
Name: E2, dtype: object

In [112]:
student.iloc[0:3,0:1]

     Name
E1   John
E2   Mary
E3  Alice

In [113]:
# 9. Find DataFrame shape and dtypes.
df.shape
df.dtypes

Name                 object
Employee_Age          int64
country              object
new_cloumn_series     int64
dtype: object

In [123]:
# 10. Handle missing values using fillna().

rough_df=pd.DataFrame(
    {
        "name":["vaishnavi",np.nan],
        "gender":[np.nan,"female"]
    }
)
print(rough_df)
print(rough_df.fillna(2))

        name  gender
0  vaishnavi     NaN
1        NaN  female
        name  gender
0  vaishnavi       2
1          2  female